- name: Run Node.js App
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt cache and install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
      update_cache: yes  # <- this is now correctly aligned with 'apt'

    - name: Clone the GitHub repository
      git:
        repo: "https://github.com/AditiAjitSalvi/College-Practical.git"
        dest: /opt/node-app
        force: yes

    - name: Install app dependencies
      command: npm install
      args:
        chdir: /opt/node-app/app

    - name: Run the Node.js app
      command: node index.js
      args:
        chdir: /opt/node-app/app
