- name: Deploy Node.js App
  hosts: localhost
  become: yes
  tasks:
    # Step 1: Install Node.js and npm
    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present
      tags: node

    - name: Install npm
      apt:
        name: npm
        state: present
      tags: node

    # Step 2: Ensure app directory exists
    - name: Ensure app directory exists
      file:
        path: /opt/node-app
        state: directory

    # Step 3: Pull or Copy app files from GitHub
    - name: Pull app files from GitHub
      git:
        repo: "https://github.com/AditiAjitSalvi/College-Practical.git"
        dest: /opt/node-app
        version: master
        force: yes

    # Step 4: Install dependencies (if any)
    - name: Install dependencies (if any)
      command: npm install
      args:
        chdir: /opt/node-app/

    # Step 5: Run the Node.js app (index.js)
    - name: Run the Node.js app
      command: /usr/bin/node /opt/node-app/app/index.js
      async: 0
      poll: 0
      tags: run-app
