- name: Run Node.js App
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js from NodeSource repository
      apt:
        name: "https://deb.nodesource.com/setup_16.x"
        state: present
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Clone the GitHub repository
      git:
        repo: "https://github.com/AditiAjitSalvi/College-Practical.git"
        dest: /opt/node-app
        force: yes

    - name: Install app dependencies
      command: npm install
      args:
        chdir: /opt/node-app

    - name: Run the Node.js app in the background using nohup
      command: nohup node /opt/node-app/index.js &
