- name: Deploy Node.js App
  hosts: localhost
  become: yes  # This will use sudo without asking for a password
  tasks:
    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present
      tags: node

    - name: Install npm
      apt:
        name: npm
        state: present
      tags: node

    - name: Ensure app directory exists
      file:
        path: /opt/node-app
        state: directory

    - name: Copy app files
      copy:
        src: app/
        dest: /opt/node-app/
        mode: 0755

    - name: Install dependencies (if any)
      command: npm install
      args:
        chdir: /opt/node-app/

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/nodeapp.service
        content: |
          [Unit]
          Description=Node.js App

          [Service]
          ExecStart=/usr/bin/node /opt/node-app/index.js
          Restart=always
          User=nobody
          Environment=PORT=3000

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Node.js app
      systemd:
        name: nodeapp
        enabled: yes
        state: restarted
